spring.application.name=roles-pago-backend
spring.datasource.url=jdbc:mysql://localhost:3306/roles_pago?
useSSL=false&serverTimezone=America/Guayaquil
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

